export declare const config: {
    TELEGRAM_BOT_TOKEN: string;
    ALLOWED_USER_IDS: number[];
    ALLOWED_GROUP_IDS: number[];
    WORKSPACE_DIR: string;
    DATA_DIR: string;
    CLAUDE_EXECUTABLE_PATH: string;
    CLAUDE_USE_BUNDLED_EXECUTABLE: boolean;
    CLAUDE_SDK_LOG_LEVEL: "off" | "basic" | "verbose" | "trace";
    CLAUDE_SDK_INCLUDE_PARTIAL: boolean;
    CLAUDE_REASONING_SUMMARY: boolean;
    BOT_NAME: string;
    BOT_MODE: "dev" | "prod";
    CLAUDE_DEFAULT_MODEL: string;
    STREAMING_MODE: "streaming" | "wait";
    STREAMING_DEBOUNCE_MS: number;
    MAX_MESSAGE_LENGTH: number;
    TTS_ENABLED: boolean;
    TTS_PROVIDER: "groq" | "openai";
    TTS_NONENGLISH_OPENAI_FALLBACK: boolean;
    TTS_MODEL: string;
    TTS_VOICE: string;
    TTS_INSTRUCTIONS: string;
    TTS_SPEED: number;
    TTS_MAX_CHARS: number;
    TTS_RESPONSE_FORMAT: string;
    IMAGE_MAX_FILE_SIZE_MB: number;
    DANGEROUS_MODE: boolean;
    MAX_LOOP_ITERATIONS: number;
    REDDITFETCH_JSON_THRESHOLD_CHARS: number;
    REDDIT_ENABLED: boolean;
    REDDITFETCH_PATH: string;
    REDDITFETCH_TIMEOUT_MS: number;
    REDDITFETCH_DEFAULT_LIMIT: number;
    REDDITFETCH_DEFAULT_DEPTH: number;
    VREDDIT_ENABLED: boolean;
    REDDIT_VIDEO_MAX_SIZE_MB: number;
    TELEGRAPH_ENABLED: boolean;
    MEDIUM_ENABLED: boolean;
    MEDIUM_TIMEOUT_MS: number;
    MEDIUM_FILE_THRESHOLD_CHARS: number;
    FREEDIUM_HOST: string;
    FREEDIUM_RATE_LIMIT_MS: number;
    GROQ_TRANSCRIBE_PATH: string;
    TRANSCRIBE_ENABLED: boolean;
    VOICE_SHOW_TRANSCRIPT: boolean;
    VOICE_MAX_FILE_SIZE_MB: number;
    VOICE_LANGUAGE: string;
    VOICE_ALLOWED_LANGUAGES: string[];
    VOICE_FIRST_MODE_ENABLED: boolean;
    VOICE_TIMEOUT_MS: number;
    TRANSCRIBE_FILE_THRESHOLD_CHARS: number;
    EXTRACT_ENABLED: boolean;
    YTDLP_COOKIES_PATH: string;
    YTDLP_PROXY_LIST_PATH: string;
    EXTRACT_TRANSCRIBE_TIMEOUT_MS: number;
    CONTEXT_SHOW_USAGE: boolean;
    CONTEXT_NOTIFY_COMPACTION: boolean;
    LATENCY_MARKER_ENABLED: boolean;
    LATENCY_MARKER_MIN_MS: number;
    TERMINAL_UI_DEFAULT: boolean;
    ALLOW_PRIVATE_NETWORK_URLS: boolean;
    LOG_AGENT_HOOKS: boolean;
    CANCEL_ON_NEW_MESSAGE: boolean;
    AGENT_WATCHDOG_ENABLED: boolean;
    AGENT_WATCHDOG_WARN_SECONDS: number;
    AGENT_WATCHDOG_LOG_SECONDS: number;
    AGENT_QUERY_TIMEOUT_MS: number;
    VOICE_AGENT_HARD_CAP_MS: number;
    INPUT_AUTODISPATCH_ENABLED: boolean;
    INPUT_AUTODISPATCH_MAX_ATTEMPTS: number;
    INPUT_AUTODISPATCH_LONG_VOICE_CHARS: number;
    TOOL_BUDGET_VOICE: number;
    TOOL_BUDGET_TEXT: number;
    AGENT_RESPONSE_TIMEOUT_MS: number;
    HANDLER_LONG_RUNNING_HEARTBEAT_MS: number;
    HANDLER_LONG_RUNNING_MESSAGE: string;
    ADAPTIVE_TIMEOUT_QUEUE_THRESHOLD: number;
    ADAPTIVE_TIMEOUT_STEP_RATIO: number;
    ADAPTIVE_TIMEOUT_FLOOR_RATIO: number;
    AGENT_WATCHDOG_USER_NOTIFY: boolean;
    AGENT_WATCHDOG_USER_NOTIFY_MESSAGE: string;
    DOCUMENT_INBOX_ENABLED: boolean;
    DOCUMENT_MAX_FILE_SIZE_MB: number;
    BOT_TOOLS: string[];
    BOT_DISALLOWED_TOOLS: string[];
    BOT_NEXUS_MAIL_MCP_COMMAND: string;
    BOT_SETTING_SOURCES: string[];
    BOT_PD_ENABLED: boolean;
    BOT_PD_DEXMASTER_MODE: "suggest" | "auto";
    BOT_PD_CATEGORIES: string[];
    BOT_PD_AGENTS: string[];
    BOT_PD_CONSOLE_ENABLED: boolean;
    BOT_PD_SPARRING_ENABLED: boolean;
    BOT_PD_COUNCIL_MAX: number;
    BOT_PD_MAX_PARALLEL: number;
    BOT_PD_OUTCOMES_DIR: string;
    BOT_PD_OUTCOME_FORMAT: "markdown" | "simple";
    BOT_MINIMAL_COMMANDS: boolean;
    BOT_COMMAND_LANGUAGE: string;
    FOLLOWUP_BUTTONS_ENABLED: boolean;
    SCANNER_PRO_WATCHER_ENABLED: boolean;
    SCANNER_PRO_WATCHER_INTERVAL_MS: number;
    SCANNER_PRO_SCRIPT_PATH: string;
    OMI_BRIDGE_WATCHER_ENABLED: boolean;
    OMI_BRIDGE_WATCHER_INTERVAL_MS: number;
    OMI_BRIDGE_PIPELINE_MIN_INTERVAL_MS: number;
    OMI_BRIDGE_OCR_MIN_INTERVAL_MS: number;
    OMI_BRIDGE_NER_MIN_INTERVAL_MS: number;
    OMI_BRIDGE_TASKS_MIN_INTERVAL_MS: number;
    OMI_BRIDGE_PIPELINE_SCRIPT_PATH: string;
    OMI_BRIDGE_OCR_SCRIPT_PATH: string;
    OMI_BRIDGE_NER_SCRIPT_PATH: string;
    OMI_BRIDGE_TASKS_SCRIPT_PATH: string;
    ANTHROPIC_API_KEY?: string | undefined;
    OPENAI_API_KEY?: string | undefined;
    REDDIT_CLIENT_ID?: string | undefined;
    REDDIT_CLIENT_SECRET?: string | undefined;
    REDDIT_USERNAME?: string | undefined;
    REDDIT_PASSWORD?: string | undefined;
    GROQ_API_KEY?: string | undefined;
    BOT_MEMORY_PROJECT?: string | undefined;
    BOT_SOUL_FILE?: string | undefined;
    BOT_WELCOME_FILE?: string | undefined;
    TELEGRAM_API_SERVER_URL?: string | undefined;
    NEXUS_MEMORY_SCOPE?: "public" | "self_private" | "operator_all" | undefined;
};
export type Config = typeof config;
//# sourceMappingURL=config.d.ts.map